name: build dev container

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEV_CONTAINER_TOKEN }}

      - name: Build and push dev container
        run: |
          # Assign github.actor to a shell variable
          username=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')

          # Build the container
          docker build -t ghcr.io/$username/neodev_env:latest .

          # Push the container
          docker push ghcr.io/$username/neodev_env:latest